[package]
name = "panda-re"
version = "0.1.0"
authors = ["Jordan McLeod <Jordan.McLeod@ll.mit.edu>"]
edition = "2018"

[lib]
name = "panda"

[dependencies]
panda-sys = { path = "../panda-sys" }
panda-macros = { path = "../panda-macros" }
inventory = "0.1.8"
dirs = "3.0.1"
lazy_static = "1.4.0"
libloading = "0.6.2"
paste = "1.0.0"
glib-sys = "0.10.0"

[features]
libpanda = ["panda-sys/libpanda"]
x86_64 = ["panda-sys/x86_64"]
i386 = ["panda-sys/i386"]
arm = ["panda-sys/arm"]
ppc = ["panda-sys/ppc"]
mips = ["panda-sys/mips"]
mipsel = ["panda-sys/mipsel"]

default = ["x86_64"]
