[package]
name = "panda"
version = "0.1.0"
authors = ["Jordan McLeod <Jordan.McLeod@ll.mit.edu>"]
edition = "2018"

[dependencies]
panda-sys = { path = "../panda-sys" }
panda-macros = { path = "../panda-macros" }
inventory = "0.1.8"
dirs = "3.0.1"

[features]
libpanda = ["panda-sys/libpanda"]
